### ISSUE TITLE
mvp-cockpit: Error during execution of step 1 (fs.btrfs) when deploying S3

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#94] opened 2016-12-05 16:29 UTC
Below blueprint was used for deploying an S3 API interface:
```
disk.ovc__disk1:
  description: 'testing purposes'
  size: 10

s3__s34yves02:
  vdc: vdc4yves02
  disk:
    - disk1
  domain: 's34yves02.aydo2.com'
``` 

Executing `ays run`:
```
root@vm-61:/optvar/cockpit_repos/yves02# ays run
Compute dependency graph...
RUN:88d31c290ebf6daba564ef541db1700f
-------
## step:1

step:1 (new)
- fs.btrfs                  data                      ! autoscale       (new)

## step:2

step:2 (new)
- caddy_proxy               proxy                     ! install         (new)
- vfs_config                opt                       ! install         (new)
- disk.ovc                  disk1                     ! install         (new)

## step:3

step:3 (new)
- node.ovc                  s34yves02                 ! install         (new)
- s3                        s34yves02                 ! install         (new)

## step:4

step:4 (new)
- os.ssh.ubuntu             s34yves02                 ! install         (new)

## step:5

step:5 (new)
- fs.g8osfs                 fuse                      ! install         (new)
- fs.btrfs                  data                      ! install         (new)

## step:6

step:6 (new)
- node.docker               caddy                     ! install         (new)
- node.docker               app                       ! install         (new)

## step:7

step:7 (new)
- os.ssh.ubuntu             caddy                     ! install         (new)
- os.ssh.ubuntu             app                       ! install         (new)

## step:8

step:8 (new)
- scality                   app                       ! install         (new)
- caddy                     caddy                     ! install         (new)


Do you want to execute this run ? (y/n):y
[Mon05 16:24] - ...umpScale/baselib/jobcontroller/Run.py:72   - INFO     - execute job: fs.btrfs!data (autoscale)
Error of job: fs.btrfs!data (autoscale):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/fs.btrfs/autoscale.py", line 9, in action
    code, out, err = cuisine.core.run('btrfs filesystem  usage -b {}'.format(service.model.data.mount), die=False)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1033, in run
    if "cygwin" in self.uname:
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1251, in uname
    self._uname = self._executor.execute("uname -a", showout=False)[1].lower()
  File "/opt/jumpscale8/lib/JumpScale/tools/executor/ExecutorSSH.py", line 173, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 251, in execute
    ch = self.transport.open_session()
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 179, in transport
    "Could not connect to %s:%s" % (self.addr, self.port))
JSExceptions.RuntimeError: ERROR: Could not connect to :2200 ((type:runtime.error)


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/opt/jumpscale8/bin/ays", line 538, in <module>
    cli()
  File "/opt/jumpscale8/bin/ays", line 46, in run
    run.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Run.py", line 261, in execute
    raise j.exceptions.RuntimeError("Error during execution of step %d\n See stacktrace above to identify the issue" % step.dbobj.number)
JSExceptions.RuntimeError: ERROR: Error during execution of step 1
 See stacktrace above to identify the issue ((type:runtime.error)
```

**Comment by xmonader** [comment] 2016-12-05 20:54
It's trying to connect on port 2200, but the image of portforwards I saw it forwards 7122 not 2200 to 22

**Comment by yveskerwyn** [comment] 2016-12-05 20:59
No that's not the problem I think, let's further discuss tomorrow...

**Comment by zaibon** [comment] 2016-12-06 04:55
>Could not connect to :2200 

This show that it's trying to connect to to a node but it doesn''t know whats the IP is. It should show `couldn't connect to `xxx.xxx.xxx.xxx:2200`

Can you inspect your services and make sure the node have an ip in the schema ?

**Comment by yveskerwyn** [comment] 2016-12-06 08:48
Maybe related to this:

![screen shot 2016-12-06 at 09 48 33](https://cloud.githubusercontent.com/assets/13795109/20918830/31ffc4a4-bb99-11e6-8aa2-5d4c271cd36b.png)

**Comment by rkhamis** [comment] 2016-12-06 08:54
Yes. That would do it. Will close this as a thank-god-that's-not-our-issue

**Comment by muhamadazmy** [comment] 2016-12-06 10:41
I think the problem is it tries to create a btrfs filesystem in the first step. While the machine creation is not done yet. IMHO the steps calculation went wrong at some point

**Comment by muhamadazmy** [comment] 2016-12-07 11:10
Fixed,
please use the blue print example from this doc
https://github.com/Jumpscale/ays_jumpscale8/blob/8.1.0/templates/app/s3/REAME.md

**Closed by muhamadazmy** 2016-12-07 11:10 UTC
Labels: state_inprogress, type_bug
