### ISSUE TITLE
mvp-cockpit: vdc actor doesn't set the capacity limits

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#74] opened 2016-11-24 09:28 UTC
The current implementation of the VDC actor is very limited, not even good enough any more for demos, it provides less functionality than [the archived one](https://github.com/Jumpscale/ays_jumpscale8/blob/archive/_ovc/vdc/schema.hrd)

We need urgently need to implement the schema as requested here [#56](https://github.com/Jumpscale/ays_jumpscale8/issues/56)

**Comment by rkhamis** [comment] 2016-11-27 10:37
Duplicate of https://github.com/Jumpscale/ays_jumpscale8/issues/56

**Closed by rkhamis** 2016-11-27 10:37 UTC
Labels: priority_critical, type_bug
