### ISSUE TITLE
node.docker portforwards are duplicated

### ISSUE THREAD

**Issue by rkhamis** [Jumpscale/ays_jumpscale8#11] opened 2016-05-26 16:03 UTC
Having two instances of node.docker services consuming a node.ovc instance will have the same portforwards, which produces an error of ports already being allocated

**Comment by xmonader** [comment] 2016-06-02 09:05
The problem is caused by the test_jumpscale_main service as it creates 2 node.docker with the same portforwards without mapping it explicitly.

**Comment by zaibon** [comment] 2016-06-02 09:14
We can't close this. The bug is still there. If we don't map explicitly the port then AYS need to find free port and make the port forward properly.

**Comment by zaibon** [comment] 2016-06-14 07:57
fixed in : https://github.com/Jumpscale/ays_jumpscale8/pull/24

**Closed by zaibon** 2016-06-14 07:57 UTC
