### ISSUE TITLE
node.ovc schema update

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#57] opened 2016-09-29 13:54 UTC
In bold what I propose to add, and everything that I propose to remove starts with //

**displayName = type:str default:''**
description = type:multiline default:''
disk.size = type:int descr:'boot disk sizes: 20,40,80,100 (GB)' default:10
// datadisks = type:str list descr:'data disks in GB'
**datadisks = type:str list consume:datadisk:1**
os.size = type:int default:2
os.image = type:str default:'Ubuntu 15.10'
ports = type:str list
sshkey = descr:'authorized sshkey for root access by system' consume:sshkey:1:1 auto
vdc = type:str parent:vdc auto

**Comment by rkhamis** [comment] 2016-11-27 12:55
Duplicate of https://github.com/Jumpscale/ays_jumpscale8/issues/56

**Closed** 2016-11-27 12:55 UTC
Labels: type_feature

**Comment by yveskerwyn** [comment] 2016-11-27 14:09
OK, but for the future we need a solution for allowing spaces in the name of a VM, and since it will not be implemented through displayName, we need to come up with another solution, see feature request: https://github.com/Jumpscale/ays_jumpscale8/issues/78
